#' @title Leghorn data
#' @description Weights of 20 Leghorn chicks
#' @format A data frame with three variables:
#' \describe{
#'   \item{x}{Weight, in grams}
#'   \item{z1}{Transformed values based on normal with mean 200 and SD 35}
#'   \item{z2}{Transformed values based on normal using sample mean and SD}
#' }
#' @source D'Agostino and Stephens (1986) page 98
"leghorn"

#' @title Beta-distributed data
#' @description Some randomly-generated Beta(1.2,1) data for testing against normality
#' @format Vector of 50 observations
#' @source Generated by package author
"beta_data"

#' @title Data on a circle
#' @description TIny sample of values on circle of circumference 1.
#' Used to illustrate that moving these values around the circle (eg.
#' by subtracting 0.25 from all of them, which, in a clockwise orientation, will change the origin from
#' North to East) the statistics V and U-squared will not change, even though the others
#' change.
#' @format Vector of 4 observations
#' @source D'Agostino and Stephens (1986) page 107
"circle"
