#' @title Leghorn data
#' @description Weights of 20 Leghorn chicks
#' @format A data frame with three variables:
#' \describe{
#'   \item{x}{Weight, in grams}
#'   \item{z1}{Transformed values based on normal with mean 200 and SD 35}
#'   \item{z2}{Transformed values based on normal using sample mean and SD}
#' }
#' @source D'Agostino and Stephens (1986) page 98
"leghorn"

#' @title Beta-distributed data
#' @description Some randomly-generated Beta(1.2,1) data for testing against normality
#' @format Vector of 50 observations
#' @source Generated by package author
"beta_data"
